language: java
env:
  matrix:
  - IDEA_VERSION=IC-15.0.4
  - IDEA_VERSION=LATEST-EAP-SNAPSHOT
jdk:
    - oraclejdk7
script:
    - ./gradlew test -PideaVersion=$IDEA_VERSION
notifications:
  email: false